### ISSUE TITLE
conekta.errors.parameter_validation.combo.order.currency_type.card.minimum

### ISSUE THREAD

**Issue by ioannis85** [conekta/conekta-node#106]
Buenas tardes.
al momento de querer realizar una orden con un pago con tarjeta obtengo el error : 
```
{ http_code: 422,
  details: 
   [ { debug_message: 'The order amount does not match with the sum of charges amounts.',
       message: 'The order amount does not match with the sum of charges amounts.',
       param: 'amount',
       code: 'conekta.errors.parameter_validation.combo.order.amount.invalid_charges_amount' },
     { debug_message: 'The amount has to be at least 3.00 MXN.',
       message: 'The amount has to be at least 3.00 MXN.',
       param: 'amount',
       code: 'conekta.errors.parameter_validation.combo.order.currency_type.card.minimum' } ],
  object: 'error',
  type: 'parameter_validation_error'
}
```

el request es el siguiente:
```
{ currency: 'MXN',
  customer_info: { customer_id: 'cus_2nrUSwLPeXjg2W7wv' },
  line_items: [ { name: 'subway de pollo', unit_price: 500, quantity: 1 } ],
  charges: [ { amount: 500, payment_method:  {
          type: "default"
        }
 } ]
 }
```

Método que ejecuto: **conekta.Order.create.**

**Como observación estoy en el ambiente de pruebas**

La verdad que no entiendo que quiere decir ese error, ya que modificó los montos y no paso de ahí. Agradeceria su ayuda

**Comment by ioannis85** [comment]
Actualización.

me acabo de dar cuenta que en el ambiente de desarrollo cuando introduzco el importe de  $500 MXN, me lo estan tomando como si fueran 5.00 MXN. Saben a que se debe eso?.  Realizé operaciones con montos mayores por ejemplo $10000  y me lo tomó como si fueran $100.00 y se pudo realizar la transacción, pero si me deja dudas esto que esta pasando

**Comment by silvaGarduno** [comment]
Hola @ioannis85 , Conekta guarda las cantidades en centavos, si quieres mandar una cantidad de 500MX tendrías que enviar 50000, con respecto a los demás errores ya los pudiste resolver?

**Comment by ioannis85** [comment]
> Hola @ioannis85 , Conekta guarda las cantidades en centavos, si quieres mandar una cantidad de 500MX tendrías que enviar 50000, con respecto a los demás errores ya los pudiste resolver?

Si, El error se presentaba ya que ignoraba que los montos dentro de la api son en centavos "**cosa que se deberia de tocar mas a fondo en la documentación"**. ya con eso todo funcionó correctamente. Saludos
