### ISSUE TITLE
Unable to createPaymentSource

### ISSUE THREAD

**Issue by klosterlight** [conekta/conekta-node#109]
I'm using node 10 on firebase functions.
conekta version **1.6.5**

I'm trying to create a paymentSource for a client but I keep getting 
**TypeError: customer.createPaymentSource is not a function**

My code

`conekta.Customer.find(customer_id, (err, customer) => {
          customer.createPaymentSource({
            type: 'card',
            token_id: token
          }, (err, res) => {
            if (err)
              info(err)
            info(res)
            updateCustomer(customer, {default_payment_source_id: res.id})
            return
          });
        })`

My customer instance
{"_id":"cus_2o41PL41nG5kyJptJ","classUrl":"/customers","children_resources":{"cards":"Card","subscription":"Subscription"},"_json":{"id":"cus_2o41PL41nG5kyJptJ","name":"a","email":"g@g.com","phone":null,"livemode":false,"default_card_id":null,"cards":[],"subscription":null,"object":"customer","created_at":1594960527},"_items":[],"cards":[],"severity":"INFO","message":""}

**Comment by klosterlight** [comment]
I can see that the documentation has been updated I'll try with the new method to see if I'm able to add payment source

**Comment by josmontes** [comment]
Hello @klosterlight ! I'm facing the same error, did you find any solution? Thanks in advance.

**Comment by klosterlight** [comment]
@josmontes I was unable to use the conekta-node version, so I ended up using the API directly with HTTP calls with axios, using the CURL documentation

**Comment by josmontes** [comment]
@klosterlight Thanks man, I'll give it a try, already sent them an email hoping they'll look into the issue.

**Comment by josmontes** [comment]
@klosterlight Hey, would you be willing to show me an example of a call you used? I'm having problems with the authentication.
I'm using it like this:
`const axios = require("axios");

const conekta = async (
  url,
  method = "GET",
  data = null,
  headers = {
    "Content-type": "application/json",
    Accept: "application/vnd.conekta-v2.0.0+json",
    Authorization: "Basic " + "key_UyYgAuMRM4ZkCfqTkiFisQ:",
  }
) => {
  try {
    const response = await axios({
      method,
      url,
      data: JSON.stringify(data),
      headers,
    });
    return response;
  } catch (err) {
    console.log(err);
    throw err;
  }
};

module.exports = conekta;`

**Comment by luismasg** [comment]
it looks like it didnt work becuase you are not handling the error.
