### ISSUE TITLE
Error al tratar de hacer un reembolso

### ISSUE THREAD

**Issue by cosio55** [conekta/conekta-node#11]
Hola, cuando trato de hacer un 'reembolso' desde este plugin para Node.js siempre recibo este error:

```
0160315-18:38:05.593(-6)? (STDERR) TypeError: undefined is not a function
W20160315-18:38:05.594(-6)? (STDERR)     at Object.custom.next (.meteor/local/isopacks/npm-container/npm/node_modules/conekta/lib/conekta.js:341:17)
W20160315-18:38:05.594(-6)? (STDERR)     at Request._callback (.meteor/local/isopacks/npm-container/npm/node_modules/conekta/lib/conekta.js:107:18)
W20160315-18:38:05.594(-6)? (STDERR)     at Request.self.callback (.meteor/local/isopacks/npm-container/npm/node_modules/conekta/node_modules/request/request.js:368:22)
W20160315-18:38:05.594(-6)? (STDERR)     at Request.emit (events.js:98:17)
W20160315-18:38:05.594(-6)? (STDERR)     at Request.<anonymous> (.meteor/local/isopacks/npm-container/npm/node_modules/conekta/node_modules/request/request.js:1219:14)
W20160315-18:38:05.594(-6)? (STDERR)     at Request.emit (events.js:117:20)
W20160315-18:38:05.594(-6)? (STDERR)     at IncomingMessage.<anonymous> (.meteor/local/isopacks/npm-container/npm/node_modules/conekta/node_modules/request/request.js:1167:12)
W20160315-18:38:05.594(-6)? (STDERR)     at IncomingMessage.emit (events.js:117:20)
W20160315-18:38:05.594(-6)? (STDERR)     at _stream_readable.js:944:16
W20160315-18:38:05.594(-6)? (STDERR)     at process._tickCallback (node.js:448:13)
```

El reembolso sí se realiza (o por lo menos eso se ve en su administrador) pero en la función siempre me regresa ese error, quería saber si hay algo que tengo que hacer o porqué estoy recibiendo este error, gracias.

**Comment by leofischer** [comment]
@julianceballos, @Janee, podrian echar un ojo?

**Comment by jcebXD** [comment]
Hola Cosio, podrías agregar la información que estas mandando o un id para revisar?

**Comment by cosio55** [comment]
Hola, actualicé a la última versión y tengo el mismo problema, como estoy llamando para hacer la devolución es:

```
conekta.Charge.find(idPagoConekta, function(err, charge) {
        charge.refund(function(err, res) {
          if(err){
            console.log('Error ')
            console.log(err)
          }
          if(res){
            console.log('Resultado: ')
            console.log(res.toObject());
          }
        });
      });
```

Y cuando lo corro con este ID por ejemplo 57631c9fa97880552a00166b obtengo este resultado en la consola:

W20160712-19:15:32.150(-5)? (STDERR) TypeError: undefined is not a function
W20160712-19:15:32.151(-5)? (STDERR)     at Object.custom.next (/.meteor/local/isopacks/npm-container/npm/node_modules/conekta/lib/conekta.js:342:9)
W20160712-19:15:32.151(-5)? (STDERR)     at Request._callback (/.meteor/local/isopacks/npm-container/npm/node_modules/conekta/lib/conekta.js:109:12)
W20160712-19:15:32.152(-5)? (STDERR)     at Request.self.callback (/.meteor/local/isopacks/npm-container/npm/node_modules/request/request.js:368:22)
W20160712-19:15:32.152(-5)? (STDERR)     at Request.emit (events.js:98:17)
W20160712-19:15:32.152(-5)? (STDERR)     at Request.<anonymous> (/.meteor/local/isopacks/npm-container/npm/node_modules/request/request.js:1219:14)
W20160712-19:15:32.152(-5)? (STDERR)     at Request.emit (events.js:117:20)
W20160712-19:15:32.153(-5)? (STDERR)     at IncomingMessage.<anonymous> (/.meteor/local/isopacks/npm-container/npm/node_modules/request/request.js:1167:12)
W20160712-19:15:32.153(-5)? (STDERR)     at IncomingMessage.emit (events.js:117:20)
W20160712-19:15:32.153(-5)? (STDERR)     at _stream_readable.js:944:16
W20160712-19:15:32.153(-5)? (STDERR)     at process._tickCallback (node.js:458:13)

**Comment by cosio55** [comment]
Algo que también está muy raro es que en el sistema sí se hace la devolución, pero en mi programa nunca sé qué pasa porque sólo aparece este error.

**Comment by jcebXD** [comment]
Hola Cosio, ya está corregido el bug, podrías probar?. Saludos.

**Comment by cosio55** [comment]
La última versión ya resolvió el problema! Gracias
