### ISSUE TITLE
Is @types/conekta available?

### ISSUE THREAD

**Issue by jeanmayorga** [conekta/conekta-node#110]
I have a project in typescript. So when i installed `conekta` and i want to import it in VScode, it's alert me about the types.

The quick solution is create a .d.ts file and write `declare module "conekta";` but i hope someday you'll have types.

![image](https://user-images.githubusercontent.com/2263749/89207798-ef90dd00-d580-11ea-9d46-7f681a4d02ee.png)

**Comment by masanchez91** [comment]
were you able to implement **conekta** for **typescript**?

**Comment by fcarrero** [comment]
no yet, im working on it , expects this soon

**Comment by angelcervera** [comment]
@fcarrero Closed because you finished it or because you are not going to do it? If you do it, from where to import the types? `npm i --save-dev @types/conekta` does not work.
