### ISSUE TITLE
customer.createSubscription

### ISSUE THREAD

**Issue by CarlosFloresSpoke** [conekta/conekta-node#117]
Me he basado en la siguiente documentación https://developers.conekta.com/page/suscripciones-con-tarjeta obteniendo el siguiente código en nodejs

customer = conekta.Customer.create({
        'name': nom,
        'email': email,
        'phone': tel,
        'metadata': { 'description': 'Compra de SUbscripción por 30 días Streaming', 'reference': '1334523452345' },
        'payment_sources': [{
          'type': 'card',
          'token_id': token
        }]
      }, function(err, res) {
          if(err){
            console.log(err);
            return;
          }
          console.log(res.toObject());
      });

     customer.createSubscription({
        "plan": "MiPlan"
      }, function(err, res) {
            console.log(res.toObject());
      });
Esto tendría que funcionar teoricamente, porque el usuario me lo crea correctamente, pero cuando entra a la funcion de customer.createSubscription manda el siguiente error TypeError: Customer.createSubscription is not a function

pero el customer si lo crea e imprime todo correcto

**Comment by eduardolabo** [comment]
Para usar createSubscription necesitas crear una instancia del cliente.

`try{
    const customer = await conekta.Customer.get({},'//customerID')
    const subscription=await customer.createSubscription({
      plan:"//planMensualID",
      payment_method:{        "type": "default"       }
    })
    console.lo(subscription)
  }
  catch(e){
    res.send(subscription)
  }`

**Comment by fcarrero** [comment]
> createSubscription

probando de esta manera

```
conekta.Customer.create({
        name: 'James Howlett',
        email: 'james.howlett@forces.gov',
        payment_sources: [{
          token_id: "tok_test_visa_4242",
          type: "card"
        }]
      }, (err, res) => {
        temp_customer = res
        temp_customer.createSubscription({
          plan: 'gold-plan'
        }, (err, res) => {}
```

**Comment by fcarrero** [comment]
ticket cerrado debido a inactividad
