### ISSUE TITLE
message_to_purchaser says amount must be in cents

### ISSUE THREAD

**Issue by arturojain** [conekta/conekta-node#12]
The message to purchaser shouldn't say the amount must be in cents since he/she is probably not using cents as their amount.

**Comment by Janee** [comment]
Hi @arturojain,
Can you sent us a example to soporte@conekta.io to review this issue?

**Comment by arturojain** [comment]
@Janee the message was sent and I was told that it would be directed to the development team.

**Comment by Janee** [comment]
Hi @arturojain will you provide me the case number of your ticket?

**Comment by arturojain** [comment]
Caso #: 41906
