### ISSUE TITLE
conekta.errors.parameter_validation.payment_sources.invalid_datatype

### ISSUE THREAD

**Issue by mxmarva** [conekta/conekta-node#124]
Hola colegas, les comparto el siguiente problema.

Cuando intento crear un pago recurrente a través de SPEI recibo el siguiente error:

`{
    "details": [
        {
            "debug_message": "Invalid datatype for \"payment_sources\" expecting at least normal Array.",
            "message": "\"payment_sources\" tiene un tipo inválido.",
            "param": "payment_sources",
            "code": "conekta.errors.parameter_validation.payment_sources.invalid_datatype"
        }
    ],
    "object": "error",
    "type": "parameter_validation_error",
    "log_id": "63a15477441a9f001739b39b"
}`

Sin embargo por más que he verificado en apariencia la solicitud esta como lo solicita la documentación, la solicitud es esta:

`curl --location --request POST 'https://api.conekta.io/customers' \
--header 'accept: application/vnd.conekta-v2.0.0+json' \
--header 'content-type: application/json' \
--header 'Authorization: Basic xxxxxxxxxxxx' \
--data-raw '{
    "name": "Arturo Albiter Flores",
    "email": "pagos@hospitalveterinarioalbiter.com",
    "phone": "+525556314534",
    "payment_sources": {
        "type": "spei_recurrent"
    }
}'`

Espero alguien me pueda hechar algo de luz al respecto.

**Comment by fcarrero** [comment]
hola @mxmarva basados en la [documentación](https://developers.conekta.com/reference/crear-cliente) el atributo `payment_sources` es un array pero en el curl que nos comparte el `payment_sources` esta como objeto

**Comment by fcarrero** [comment]
ticket closed due to inactivity
