### ISSUE TITLE
Token object could not be found

### ISSUE THREAD

**Issue by zomars** [conekta/conekta-node#14]
The card is being tokenized correctly, but when trying to charge it it says It cannot be found.

This is the request:
```
{  
   "card":{  
      "number":"CARD_NUMBER_FOR_EXAMPLE",
      "name":"NAME_FOR_EXAMPLE",
      "exp_year":"2019",
      "exp_month":"09",
      "cvc":"EXAMPLE_CVC",
      "device_fingerprint":"vkxkuqt90d5asu4gvprxry72rz2ql7m7"
   }
}
```
I get a normal response with a new token:
```
{  
   "id":"tok_XtiGhcjcDVMwomgSE",
   "livemode":true,
   "used":false,
   "object":"token"
}
```
Then, when processing my payments this is my request:
```
{  
   "description":"Boleto para la experiencia Encounter Culiacán.",
   "amount":15000,
   "currency":"MXN",
   "reference_id":"jt-encounter_ticket-sale",
   "card":"tok_XtiGhcjcDVMwomgSE",
   "details":{  
      "name":"My name",
      "phone":"My phone",
      "email":"example@email.com",
      "line_items":[  
         {  
            "name":"Boleto",
            "description":"Example description",
            "unit_price":15000,
            "quantity":1
         }
      ]
   }
}
```
And I get this response:
```
{  
   "object":"error",
   "type":"resource_not_found_error",
   "message":"Object tok_XtiGhcjcDVMwomgSE could not be found.",
   "message_to_purchaser":"El recurso no ha sido encontrado.",
   "param":null,
   "code":null,
   "http_code":404
}
```

As you can see, I'm using the exact same token that conekta.js is giving me and for some reason it's not finding it.

Any help is deeply appreciated.

**Comment by str** [comment]
Tengo el mismo error, recibo el mensaje "El recurso no ha sido encontrado.". 

@zomars, ¿cómo lo solucionaste?

**Comment by zomars** [comment]
@str no lo recuerdo del todo bien, pero creo que mis claves de API estaban mezcladas. Procura que estén bien configuradas en el servidor.

**Comment by invasoria** [comment]
That error means a valid token can't be found. Either conekta.js is not running properly (not making any token correctly) or there is an API key mismatch.
