### ISSUE TITLE
La documentación no coincide en nada con la implementación.

### ISSUE THREAD

**Issue by kuriel-trivu** [conekta/conekta-node#144]
Hola, la documentación no coincide. Ni la documentación que tienen en su sitio ni la de Github.

Ninguna coincide con lo que existe en tiempo de ejecución.

Al pasar parámetros no los toma, tiene uno que estarle atinando y la verdad no le he atinado a ninguno.

Estoy usando Typescript y ni siquiera su código está documentado.

Creo ni las versiones que tienen publicadas coinciden con las publicadas en NPM.

Honestamente, es horrible trabajar así, 

¿Cuándo lo corrigen?.

![image](https://github.com/conekta/conekta-node/assets/46456105/00c67011-7354-4813-9d1b-3aa9432f4a66)

![image](https://github.com/conekta/conekta-node/assets/46456105/d3613f6c-20d3-4264-86a2-6e863129e4b1)

![image](https://github.com/conekta/conekta-node/assets/46456105/c2b04a25-1b41-4bc3-a270-93ce9a668bda)

![image](https://github.com/conekta/conekta-node/assets/46456105/622108fa-7482-4280-b2bd-8252341fd836)

**Comment by fcarrero** [comment]
buenas, se ha lanzado una version renovada del sdk
https://www.npmjs.com/package/conekta la cual solventan esos issues

adicionalmente recalcamos, que la doc generada en el devcenter es automaticamente por parte del proveedor
