### ISSUE TITLE
Allow "get all" on endpoints

### ISSUE THREAD

**Issue by arturojain** [conekta/conekta-node#15]
Allow a method to get all data from all endpoints, not only finding a single item.

**Comment by jcebXD** [comment]
do you mean allow a function for describe which object and what to call on the api?

**Comment by arturojain** [comment]
i.e.

// get all Charges
conekta.Charge.findAll(callback);
conekta.Plan.findAll(callback);
conekta.Customer.findAll(callback);
conekta. Payee.findAll(callback);
conekta. Payout.findAll(callback);

**Comment by faridhajnal** [comment]
It would be awesome to be able to get all Customers or Orders... Is there a way to get more than one Customer/Order?

**Comment by BernardoMB** [comment]
Yes! It would be awesome and a really nice feature.

**Comment by WCLab** [comment]
You may use Array.push into a foreach with your own customers list. It is possible, and returns with promise.
