### ISSUE TITLE
opts.next is not a function on create a order

### ISSUE THREAD

**Issue by rurigk** [conekta/conekta-node#28]
/home/rurigk/git/project/node_modules/conekta/lib/conekta.js:282
          opts.next(null, this);
               ^

TypeError: opts.next is not a function
    at Object.<anonymous> (/home/rurigk/git/project/node_modules/conekta/lib/conekta.js:282:16)
    at Request._callback (/home/rurigk/git/project/node_modules/conekta/lib/conekta.js:125:12)
    at Request.self.callback (/home/rurigk/git/project/node_modules/request/request.js:368:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/rurigk/git/project/node_modules/request/request.js:1219:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/rurigk/git/project/node_modules/request/request.js:1167:12)
    at emitNone (events.js:91:20)

```
conekta.Order.create({
  "currency": "MXN",
  "customer_info": {
    "customer_id": "cus_idXXXXXXXX"
  },
  "line_items": [{
    "name": "Nombre del producto",
    "unit_price": 35000,
    "quantity": 1
  }],
  "charges": [{
    "payment_method": {
      "type": "default"
    }
  }]
})
```

**Comment by rurigk** [comment]
Please add callback argument to the NodeJS api docs

Conekta.Order.create({
  "currency": "MXN",
  "customer_info": {
    "customer_id": "cus_zzmjKsnM9oacyCwV3"
  },
  "line_items": [{
    "name": "Box of Cohiba S1s",
    "unit_price": 35000,
    "quantity": 1
  }],
  "charges": [{
    "payment_method": {
      "type": "default"
    }
  }]
},function(err,data){
  console.log(data)
})

**Comment by KarlaRobinson** [comment]
Hi! I see you have resolved your issue. Please let us know if you have any other doubts, by emailing us at soporte@conekta.com

**Comment by CarlosFloresSpoke** [comment]
Me he basado en la siguiente documentación https://developers.conekta.com/page/suscripciones-con-tarjeta obteniendo el siguiente código en nodejs

customer = conekta.Customer.create({
'name': nom,
'email': email,
'phone': tel,
'metadata': { 'description': 'Compra de SUbscripción por 30 días Streaming', 'reference': '1334523452345' },
'payment_sources': [{
'type': 'card',
'token_id': token
}]
}, function(err, res) {
if(err){
console.log(err);
return;
}
console.log(res.toObject());
});

 customer.createSubscription({
    "plan": "MiPlan"
  }, function(err, res) {
        console.log(res.toObject());
  });
Esto tendría que funcionar teoricamente, porque el usuario me lo crea correctamente, pero cuando entra a la funcion de customer.createSubscription manda el siguiente error TypeError: Customer.createSubscription is not a function

pero el customer si lo crea e imprime todo correcto
