### ISSUE TITLE
Error al eliminar método de pago

### ISSUE THREAD

**Issue by medinagarciajose** [conekta/conekta-node#29]
Hola, estoy tratando de eliminar un método de pago siguiendo su documentación pero no me funciona.

Estoy usando la última versión de esta librería y me sale este error:

```
.../ConektaService.js:44
        customer.payment_sources[0].delete(function (err, resp) {
                                   ^
TypeError: Cannot read property 'delete' of undefined
```

**Comment by KarlaRobinson** [comment]
Hola,
Para eliminar un payment source es:
customer.payment_sources.get(0).delete

Y aquí te comparto un ejemplo:
https://github.com/conekta/conekta-node/blob/master/test/test.js#L1058

Cualquier otra duda nos puedes escribir a soporte@conekta.com!

**Comment by medinagarciajose** [comment]
Genial, muchas gracias.
