### ISSUE TITLE
callbacks not 'Node style'

### ISSUE THREAD

**Issue by varffs** [conekta/conekta-node#3]
Why are the callbacks not 'Node style' AKA a single function?

It would be better if the functions were more like:

`conekta.Charge.create(params, function(error, response) {});`

Specifically in my case I'm using Meteor and want to wrap the Conekta API functions in http://docs.meteor.com/#/full/meteor_wrapasync so I can use them synchronously on the server. Having 2 separate return functions complicates this.

**Comment by julianceballos** [comment]
Hi Varffs, was just an implementation to handle success and error independently. But we love feedback and i agree with you, would be nice the same implementation with another node libraries, just handling the error parameter.

**Comment by julianceballos** [comment]
I've opened a pull request #5 , what do you think @varffs ?

**Comment by julianceballos** [comment]
Has been released with the version 1.1.0

**Comment by varffs** [comment]
Awesome. Thanks.
