### ISSUE TITLE
How i can select default payment method in nodejs

### ISSUE THREAD

**Issue by rurigk** [conekta/conekta-node#30]
Is there a method for set a default payment method?

**Comment by Memogcia** [comment]
+1 

Rurigk did you find something to update the default payment method?

**Comment by KarlaRobinson** [comment]
Hi!  Here is an example to change the default payment source:
```node
conekta.Customer.find('cus_2gJHRkVXdMeoezZnA', function(err, customer) {
var srcId = customer.toObject().payment_sources.data[0].id;
customer.update({
default_payment_source_id: srcId
}, function(err, customer) {
console.log(customer.toObject());
});
});
```

Or you can also change the default payment_source in your Conekta admin in Customer details.
If you have any other questions don't hesitate to write to soporte@conekta.com :)

**Comment by RaulUrtecho** [comment]
> Hi! Here is an example to change the default payment source:
> 
> ```js
> conekta.Customer.find('cus_2gJHRkVXdMeoezZnA', function(err, customer) {
> 	var srcId = customer.toObject().payment_sources.data[0].id;
> 	customer.update({
> 		default_payment_source_id: srcId
> 	}, function(err, customer) {
> 		console.log(customer.toObject());
> 	});
> });
> ```
> 
> Or you can also change the default payment_source in your Conekta admin in Customer details.
> If you have any other questions don't hesitate to write to [soporte@conekta.com](mailto:soporte@conekta.com) :)

I think these kind of infomation must be in the tutorial as explanation of how to change between payments_sources, to create orders, subscriptions.. etc.
