### ISSUE TITLE
When response param is null it still tries to parse it to JSON and throws exception

### ISSUE THREAD

**Issue by figalex** [conekta/conekta-node#36]
On [this line](https://github.com/conekta/conekta-node/blob/master/lib/conekta.js#L112), I've been getting 504 GATEWAY_TIMEOUT and when that happens "res" param is null and it still tries to parse it to JSON and throws an exception.

**Comment by Janee** [comment]
@eduardoconekta @JoValo ¿nos apoyan con este issue? @benitocas88 también reporta esta situación.

**Comment by benitocas88** [comment]
We have the same error in these same line

**Comment by eduardoconekta** [comment]
@Janee Claro, ya mismo lo reviso, @benitocas88 , @figalex Hi, we will work on it, thanks for share with us, some of you please can paste a snippet of your code to have a better context ?

**Comment by figalex** [comment]
@eduardoconekta en mi caso únicamente estoy creando un Customer con suscripción de la misma manera que se muestra en la documentación:
```javascript
conekta.Customer.create({
      name,
      email,
      plan_id: planId,
      payment_sources: [{
        'type': 'card',
        'token_id': cardToken
      }]
    },
```
El error que comento solo ocurrió unas 4-5 veces durante algunos minutos al ejecutar ese código por que recibía el 504 GATEWAY_TIMEOUT. Una vez que el servicio volvió a enviar la respuesta a tiempo correctamente ya no tiraba la excepción al tratar convertir a JSON la respuesta por que no era "null"

**Comment by eduardoconekta** [comment]
@figalex Me parece que la key `9YxqfRnx4sMQDnRsqdYn` de la documentación del README de git ya no esta activa por eso muestra el error, te recomiendo probar con tu private key con la cual diste de alta tu cuenta en admin.conekta.com
```
conekta.api_key = 'key_xxxxxxxxxxxxxx'
```

**Comment by figalex** [comment]
@eduardoconekta no me refería a que usé tal cual el código de la documentación, si estoy utilizando mis propios dev keys.

**Comment by eduardoconekta** [comment]
@figalex  podrias revisar que tengas seteada tu private key en conekta.api_key ? , ya que con la public key me muestra el error que comentas

**Comment by benitocas88** [comment]
Esta es la línea de código que ejecuto, al igual que @figalex estoy creando una suscripción:
`var subscription = {};
					subscription.plan = plan;
					subscription.card = card_source_id;

					customer.createSubscription(subscription, (error, subscription_created) => {
						if (error) return continuation(error);
						return continuation(null, this._scheme(subscription_created));
					});`


@eduardoconekta no creo que sea problema de las keys ya que puedo crear el customer y el payment source, de ser las keys el throw estaría generándose desde el principio, al crear el customer.

**Comment by Angel-Mu** [comment]
Que tal, yo igual ando teniendo el mismo problema, en el momento de crear una subscripción, el webhook si lo esta recibiendo pero el callback de `customer.createSubscription` no esta regresando... 

```
2017-06-26T17:09:43.931Z - error: UncaughtException!
2017-06-26T17:09:43.932Z - error: SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (node_modules/conekta/lib/conekta.js:112:49)
    at Request.self.callback (node_modules/conekta/node_modules/request/request.js:368:22)
```

**Comment by modulor** [comment]
Tenemos el mismo problema

`SyntaxError: Unexpected token u in JSON at position 0`

Actualizamos la versión de la dependencia de 3.1.0 a 3.1.1 y sí jaló la respuesta para crear una "Subscription", pero tarda demasiado en responder, aproximadamente entre 20 a 25 segundos, a veces hasta 29. Hay ocasiones en que deplano no funciona y no responde nada.

**Comment by benitocas88** [comment]
@modulor lo que en realidad debería pasar es que jale al 100% pero que tampoco se tarde tanto tiempo, no sabemos el status de este issue. @eduardoconekta

**Comment by eduardoconekta** [comment]
que tal, estamos replicando el error sin el mismo resultado aun, si pudiera alguna hacer un gist con todo su código así podríamos debuggear mas a fondo
```
let conekta = require('../lib/conekta.js')
conekta.api_key = 'key_SN2vakDK6CrWATiRWCyoZw'

const createCustomer

const createSubscription = (subscription) =>{
  return new Promise( (resolve, reject ) => {
    conekta.api_key = 'key_SN2vakDK6CrWATiRWCyoZw'
    conekta.Customer.find('cus_2gm61fGpqGdgFMRZRm',function(err,customer){
      console.log('error customer find: ', err)
      if(err) {
        resolve(JSON.stringify(err))
        return
      }
      customer.createSubscription({
        plan: 'gold-plan',
        card: 'src_2gm61fGpqGdFMRZRp'
      },
        (err,response)=>{
          console.log('error createSubscription: ', err)

          if(err){
            reject(JSON.stringify(err))
            return
          }
          console.log('response: ', response);
          resolve(null, response)
        }
      )
    })
  }
 )
}

createSubscription()
```
tenemos ademas este snippet con promise que funciona bien, por eso quisiera que pudieran pasarme su codigo por favor @benitocas88 , @Angel-Mu , @figalex

**Comment by benitocas88** [comment]
Ok, este es mi código para crear una suscripción.

```
create(customer_id, user, card_source_id, continuation) {
  Conekta.Customer.find(customer_id, (error, customer) => {
    if (error) return continuation(error);

    var difference_days = moment().diff(moment(user.createdAt), "days");
    var plan = ((user.conekta || difference_days >= 31) ? '01-Beta' : '02-Tarjeta');

    var subscription = {};
    subscription.plan = plan;
    subscription.card = card_source_id;

    customer.createSubscription(subscription, (error, subscription_created) => {
      if (error) return continuation(error);
      return continuation(null, this._scheme(subscription_created));
    });
  });
},
```
Solo determino a qué plan asigno a un customer_id y todo lo demás como dice la documentación.

**Comment by eduardoconekta** [comment]
```
let conekta = require('../lib/conekta.js')
conekta.api_key = 'key_SN2vakDK6CrWATiRWCyoZw'
customer_id = 'cus_2gm61fGpqGdFMRZRm'
card_source_id = 'src_2gm61fGpqGdFMRZRp'

function create(customer_id, user, card_source_id){
  conekta.Customer.find(customer_id, (error, customer) => {
    if (error) {
      console.log(error);
    }
    var plan = 'gold-plan' ;

    var subscription = {};
    subscription.plan = plan;
    subscription.card = card_source_id;

    customer.createSubscription(subscription, (error, subscription_created) => {
      if (error) return error;
      return subscription_created;
    });
  });
}
create(customer_id,'',card_source_id)
```
@benitocas88 podrias verificar que funcione este snippet, 
para replicarlo en tu caso antes de crear una suscripcion debes tener 
*private key 
*customer id (existente)
*payment_source id (existente)
*plan (existente)

**Comment by Angel-Mu** [comment]
En mi caso lo hago en un POST 

```
var body = req.body;
async
  .waterfall([
    function(cb) {
      var conekta_user = {
        name: body.fullname,
        email: body.email,
        phone: body.phone_number_1,
        payment_sources: [{
          type: 'card',
          token_id: body.token.id
        }],
      };
      conekta.Customer.create(conekta_user, cb);
    },
    function(customer, cb) {
      customer.createSubscription({
        plan: 'semestral'
      }, cb);
    }
  ],
  function(err, result) {
    console.log(error, result);
    if (err) {
      res.status(400).send(err);
    } else {
      res.status(200).send(result);
    }
  });
```

El user si se esta creando, ya debugge esa parte, el `customer.createSubscription` es el que esta tronando. Otra cosa a notar es tengo un webhook al que si esta llegando el postback, donde si sale que se creo la subscripción. Ademas de que, también note que funciona aleatoriamente. 
Por ejemplo ahorita acaba de funcionar, pero en la mañana no, y no he movido nada en el código.

**Comment by benitocas88** [comment]
Podrían ser que se genere en algo de back-end alguna excepción no controlada, o bien al ser JS asíncrono entonces de repente la respuesta es rápida y en otros caso no. Aunque podría ser más algo del servicios, más allá del la librería de JS

**Comment by Angel-Mu** [comment]
@eduardoconekta  Acaba de volverme a suceder! 

```
2017-06-27T17:56:35.022Z - error: UncaughtException!
2017-06-27T17:56:35.023Z - error: SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (node_modules/conekta/lib/conekta.js:112:49)
```

**Comment by modulor** [comment]
@eduardoconekta de 5 pruebas, falla 1, las otras 4 me demora como 28 segundos en responder

**Comment by eduardoconekta** [comment]
sigo sin replicarlo, quizá sea el snippet que me comentas, no se si a @benitocas88 aun le sucede con el script ?

**Comment by benitocas88** [comment]
@eduardoconekta aún no ejecuto pero dame unos minutos y te comento.

**Comment by Angel-Mu** [comment]
Debuggeando un poco mas en el npm veo que llega 
 
```
_header: 'POST /customers/cus_2gmMH3TECPWuAsCL2/subscription HTTP/1.1\r\nAccept: application/vnd.conekta-v2.0.0+json\r\nContent-Type: application/json\r\nX-Conekta-Client-User-Agent: {"bindings_version":"Conekta::3.1.1","lang":"node","lang_version":"v7.10.0","publisher":"conekta","uname":"x64 darwin 16.6.0"}\r\nUser-Agent: Conekta/v1 NodeBindings/Conekta::3.1.1\r\nAccept-Language: en\r\nAuthorization: Basic someToken=:\r\nhost: api.conekta.io\r\ncontent-length: 25\r\nConnection: close\r\n\r\n',
```
La línea que marca error es la  112 

```
request[opts.method](options, function(err, req, res) {
      // Parse response to JSON
      console.log(err);   // null
      console.log(req);  // en el header llega lo de arriba
      console.log(res);  // undefined
      res = typeof res == 'object' ? res : JSON.parse(res);  // Aqui es donde esta un error, que al parecer si es  por que res es undefined y termino en un timeout
```

**Comment by modulor** [comment]
muchas gracias por tu apoyo @eduardoconekta , ya checamos los datos y todo está bien, estoy monitoreando también el "dashboard" de conekta, el plan se relaciona con el cliente sin problemas cuando se crea una "subscription", es casi instantaneo en el dashboard de conekta, pero el problema es la respuesta del API, tarda bastante o a veces no responde

saludos

**Comment by benitocas88** [comment]
@eduardoconekta ya ejecuté el script y me marca el mismo error.

![image](https://user-images.githubusercontent.com/2643684/27604359-af51770a-5b3e-11e7-8009-e8f6c419441e.png)

**Comment by eduardoconekta** [comment]
Podrías hacerle un console log a la variable error para saber que es lo que esta regresando el api 
ya que si response es undefined error debe tener el motivo
```
function(**err**,resp)
```

**Comment by Angel-Mu** [comment]
@eduardoconekta El detalle es que en el request al momento de hacer un post subscription, algo esta pasando mal, que no se esta manejando por parte de su backend, y termina por cerrar la conexion por lo que res llega undefined y al tratar de hacer el JSON.parse(undefined) lanza ese error.
Intente modificar el timeout de `request` pero sigo sin tener éxito. Como menciona @modulor en el dashboard sale que si se creo la subscrición pero no llego el response

y con respecto a tu ultimo comentario, el error  =  null

**Comment by Angel-Mu** [comment]
```error = null 
req = undefined
```

Quien tiene un detalle es `req`

```
_header: 'POST /customers/cus_2gmMH3TECPWuAsCL2/subscription HTTP/1.1\r\nAccept: application/vnd.conekta-v2.0.0+json\r\nContent-Type: application/json\r\nX-Conekta-Client-User-Agent: {"bindings_version":"Conekta::3.1.1","lang":"node","lang_version":"v7.10.0","publisher":"conekta","uname":"x64 darwin 16.6.0"}\r\nUser-Agent: Conekta/v1 NodeBindings/Conekta::3.1.1\r\nAccept-Language: en\r\nAuthorization: Basic someToken=:\r\nhost: api.conekta.io\r\ncontent-length: 25\r\nConnection: close\r\n\r\n',
statusCode: 504,
statusMessage: 'GATEWAY_TIMEOUT',
```

**Comment by benitocas88** [comment]
@eduardoconekta en efecto, en ocasiones la suscripción es creada pero se tarda y en otras ocasiones hay error; no hace un console.log(error) ya que no llega, el throw se genera desde la librería conekta y no está controlada por lo tanto al console.log(error) no llegará

![image](https://user-images.githubusercontent.com/2643684/27604687-a7d90186-5b3f-11e7-966b-cdea81b736f2.png)

insito, es algo de servicios, como dice @Angel-Mu si le está dando un timeout entonces la api no responde y en la librería eso no está controlado

**Comment by eduardoconekta** [comment]
otra cosa que se me ocurre puede ser la version de la librería, como dice @modulor tratar de incrementar la version de la lib a la 3.1.1 desde el package json @benitocas88 , @Angel-Mu 

```
{
  "name": "conekta",
  "version": "3.1.1",
  "description": "Conekta node Wrapper",
  "keywords": [
    "conekta",
    "wrapper",
    "spei",
    "oxxo",
    "credit card",
    "payment",
    "payout",
    "subscription"
  ],
```

**Comment by Angel-Mu** [comment]
@eduardoconekta Tengo esa versión, incluso ya hice downgrade y es lo mismo! eso no es lo que esta pasando, el backend de conekta no esta regresando algo válido, ademas de que no esta manejada esa excepción

**Comment by Angel-Mu** [comment]
@eduardoconekta 

<img width="598" alt="untitled" src="https://user-images.githubusercontent.com/6799039/27611049-53a2eafc-5b56-11e7-9194-216caf4c2bef.png">

**Comment by modulor** [comment]
@eduardoconekta que versión de node estas usando?

**Comment by modulor** [comment]
hice un clone del conekta-node, instalé las dependencias e hice un npm test y esto es lo que me arroja

![imagen](https://user-images.githubusercontent.com/3484504/27611525-1848b62e-5b58-11e7-86ed-ca2f16404add.png)

**Comment by figalex** [comment]
@eduardoconekta esta es la única librería que está recibiendo timeouts? Las de python, java u otro lenguaje no están teniendo este tipo de problemas? Pregunto por que creo que si fuera algo que esta mal de parte del servicio de conekta entonces las demás librerías también tendrían problemas. No es el caso?

**Comment by eduardoconekta** [comment]
ese fail @modulor esta mapeado es por otra cuestión, podrían remplazar la funcion de la linea 112 por la siguiente logica
```
request[opts.method](options, function(err, req, res) {
      var error = null,
        result = null;

      // Check response status code for assign error or result with data
      if ((req.statusCode != 200 &&  req.statusCode != 201) || err) {
        error = _.extend({
          http_code: req.statusCode
        }, res, err);
      } else {
        result = typeof(res) == 'object' ? res : JSON.parse(res);
      }

      opts.next(error, result);
    });
  }
````

@benitocas88 , @Angel-Mu  para poder integrar el fix a master y @figalex no de hecho es la primera vez que se tiene este error, yo tengo python y php e incluso  ahora mismo y no he tenido este problema, podrían por ultimo probar  este cambio rapido en la función que contiene la linea 112 ?

**Comment by figalex** [comment]
@eduardoconekta ese cambio va a evitar que se tire la excepción (lo cual es correcto para solucionar este issue en particular pues es lo que se reportó), pero si siguen llegando como respuesta 504 GATEWAY_TIMEOUT creo que nosotros no tenemos manera de validar si se creó la suscripción (y el cargo al cliente) en ese request, a menos que hagamos el request de esta manera pero tengamos que asegurarnos en el webhook si conekta nos notificó de la suscripción creada y después de eso notificar a nuestro cliente que sí fue exitoso el pago, lo cual creo que nos obligaría a tener que usar algo como websockets para notificar a nuestro cliente.

**Comment by Angel-Mu** [comment]
@eduardoconekta No creo que sea una solución real 😢  se manejo la excepción... pero sigue sin regresar el response, eso fue como un brute force fix, si regresa a mi callback pero con un error de lado del backend de conekta 😢 

```
2017-06-27T23:10:42.089Z - info: POST - /subscription/payment/:user_id
Error while trying to precess the payment subscription, see step
{ http_code: 504 }
```

La suscripción si se realiza, lo que no hace es regresar los datos de la suscripción si no que se forza el error!

![image](https://user-images.githubusercontent.com/6799039/27614017-89e31ba6-5b64-11e7-85d8-8fe601a8725a.png)

**Comment by figalex** [comment]
@eduardoconekta tal vez una solución podría ser que en las opciones del request se ponga por default un timeout que sea igual (o tal vez mayor) al timeout que ustedes tienen definido en su servicio para generar el cargo. De esta manera la librería de node solo tiraría el error de 504 GATEWAY_TIMEOUT si el servicio de conekta también tiro un error de timeout y nosotros podríamos estar seguros de que si recibimos ese error es por que NO se generó la suscripción ni el cargo.

**Comment by benitocas88** [comment]
Cierto, que me envíe un 504 no me soluciona ahora de mi lado como debería funcionar ya que yo almaceno datos al crear dicha suscripción

**Comment by Angel-Mu** [comment]
@figalex Yo ya intente modear la librería de conekta-node para aumentar ese timeout de lado y aun así regresa lo mimso. Mi teoría es que en su backend truena algo que no estan manejando y nunca regresa, lo que hace que asi le pongamos 3 min de timeout va a seguir dando lo mismo por que no se manejo ese error

**Comment by eduardoconekta** [comment]
Es muy raro que tengan esos timeouts revise con alguien mas en el equipo todos los request de @Angel-Mu en base a su customer y ningún request tuvo timeout todos fueron 200, esos reigstros los podemos revisar en los logs de la compañía ligados al customer que les menciono cus_2g...L2 directamente en la consola del api, permítanme hoy lo que resta del dia y mañana poder darle seguimiento, por nuestro lado he estado haciendo todas las pruebas que están a mi alcance sin tener un 504 :/ , les proporciono mi correo para poder darle seguimiento mas rapido eeduardo@conekta.com, quedo atento de sus contactos por correo 👍  y muchas gracias por su tiempo

**Comment by eduardoconekta** [comment]
perdon es eenriquez@conekta.com !

**Comment by figalex** [comment]
Si esta raro, acabo de hacer pruebas usando Postman y me regresa la respuesta inmediatamente. Con los mismos datos desde mi backend con node sigo recibiendo 504 timeout.

**Comment by eduardoconekta** [comment]
si, podrías mandarme un mensaje por correo y podemos darte mas ayuda, otra cosa es correr los test, en teoría debe marcar error en todas las pruebas de subscription, por ahi me compartieron una captura pero curiosamente marcaron 52 test passed y 1 failed pero fue en order.capture

**Comment by benitocas88** [comment]
@eduardoconekta corrí el npm test del paquete y las respuestas al crear la suscripción fueron rápidas, sin embargo, sustituí con mi propia key, mi plan y mi customer_id y las pruebas de crear la suscripción fallaron

**Comment by eduardoconekta** [comment]
@benitocas88 claro, por favor 👍

**Comment by benitocas88** [comment]
@eduardoconekta listo! Solo es correr el npm test

**Comment by Angel-Mu** [comment]
@figalex como fue que le hiciste para correrlo en postman, segui tiu apporach y lo intente con `request` , `request-promise` y postman directamente y no logró que me regrese otra cosa que no sea un status 504.

@eduardoconekta tienen manera de revisar los logs de su backend? o alguna opción para hacer subscripciones directamente?

![image](https://user-images.githubusercontent.com/6799039/27649306-f9320908-5bf6-11e7-8748-8833304f8691.png)

![image](https://user-images.githubusercontent.com/6799039/27649237-c779ce32-5bf6-11e7-9e2f-9c73c57299c9.png)

**Comment by figalex** [comment]
@Angel-Mu tal cual como lo hiciste tu nomas yo hice el request a https://api.conekta.io/customers y creo el cliente con un planId para crear la suscripción.

**Comment by Angel-Mu** [comment]
@figalex algo como esto??
https://developers.conekta.com/api?language=bash#create-customer

Osea crear customer y subscription en un solo request... 🤔

**Comment by figalex** [comment]
Así es @Angel-Mu!

**Comment by eduardoconekta** [comment]
@figalex , @Angel-Mu , @benitocas88 , @modulor ya pudimos replicar el error 👍 , y recae en la forma en la que se crea un plan, si revisan en la parte de la documentación https://developers.conekta.com/api?language=node#plan  , para crear un plan se requieren todos los campos y algunos de los planes que veo por (credenciales que me pasaron) no tienen o trial_period_days o expiry count este error es nuestro y lo vamos a corregir en la parte del api, pueden resolver por el momento la parte de *trial_period_days* asignándole  el valor mínimo que acepta (1) y a **expiry_count** calcular el intervalo si es **month** seria un expiry count de (12) para que este valido por 1 año o 24 para 2 años, etc.

Muchas gracias a todos por su tiempo y reportarnos el bug.
```
Conekta.Plan.create({
    "id": "gold-plan",
    "name": "Gold Plan",
    "amount": 10000,
    "currency": "MXN",
    "interval": "month",
    "frequency": 1,
    "trial_period_days": 15,
    "expiry_count": 12
});
```

**Comment by figalex** [comment]
@eduardoconekta el **expiry_count** es la duración del plan cierto?  Cuando es "indefinido" también le ponen 12 o como lo manejan?

**Comment by benitocas88** [comment]
@eduardoconekta en nuestro caso, el plan se creó desde dashboard y manejamos igual como indefinido, aunado a eso, intentamos editar ese plan desde el dashboard y los campos están deshabilitados

**Comment by eduardoconekta** [comment]
exacto, el problema es que se diseño para que sean planes que siempre caduquen, lo cual esta mal de nuestra parte lo que podrías hacer es darle un rango alto para la expiración del plan,
y si expiry_count va ligado a interval  que puede ser ` week, half_month, month, year`

**Comment by figalex** [comment]
el **expiry_count** no tiene límite? Entonces le podemos poner 1188 meses (99 años) y de esa manera ya no expiraría nunca?

**Comment by benitocas88** [comment]
@eduardoconekta pero eso lo solucionarán cierto? es decir, si yo lo dejo tal cual como está ahora sin modificar ni nada, ustedes van a solucionar el bug

**Comment by Angel-Mu** [comment]
@eduardoconekta Yo genere todos mis planes, y en algunos seleccione sin trial_days y todos fue indefinido el expiry_count.
Intentaré generarlos con `curl` y probaré

**Comment by eduardoconekta** [comment]
@benitocas88 este bug debe estar replicado en nuestro dashboard por la parte del equipo de front-end que supuso que se podia hacer un plan ilimitado, si quieres ayuda mas personalizada para revisar ese tema con customer support  support@conekta.com

**Comment by eduardoconekta** [comment]
@Angel-Mu por favor, si, deben de ir todos los parametros

**Comment by benitocas88** [comment]
@eduardoconekta entonces en dashboard no lo van a solucionar? no entiendo bien...

**Comment by figalex** [comment]
@benitocas88 a lo que entendí, hubo un malentendido con el equipo de frontend al desarrollar esa parte del dashboard. Tal vez si se solucione mas adelante pero por el momento nosotros tenemos que asignar un expiry_count usando el API para que los planes tengan todos los campos requeridos

**Comment by eduardoconekta** [comment]
si claro,  también, por el momento si tienes algún proceso en producción con ese plan y tengas algún tema de operación puedes contactar al correo , pero si , se va a arreglar en definitivo

**Comment by figalex** [comment]
@eduardoconekta entonces para cerrar este issue, creo que si se debería agregar una validación en la línea donde se intenta hacer el `JSON.parse(res)` para no intentar parsear si es nulo (independientemente de cuál haya sido la respuesta del servicio) y regresar el error al callback en lugar de tirar una excepción.

**Comment by eduardoconekta** [comment]
Si el fix basicamente es sobre el siguiente snippet ya que underscore pasaba undefined al error siempre que res venia con ese valor despues del timeout 
```
request[opts.method](options, function(err, req, res) {
      var error = null,
        result = null;

      // Check response status code for assign error or result with data
      if ((req.statusCode != 200 &&  req.statusCode != 201) || err) {
        error = _.extend({
          http_code: req.statusCode
        }, res, err);
      } else {
        result = typeof(res) == 'object' ? res : JSON.parse(res);
      }

      opts.next(error, result);
    });
  }
```
dejo el PR
https://github.com/conekta/conekta-node/pull/37
gracias de nuevo, cierro el issue

**Comment by modulor** [comment]
@eduardoconekta muchas gracias, voy a probar de nuevo. Por cierto, los planes los estaba creando directamente en el dashboard de "conekta".

Saludos

**Comment by modulor** [comment]
acabo de crear un plan con estas características, hice el procedimiento para crear una "Subscription" y jaló de volada!
![imagen](https://user-images.githubusercontent.com/3484504/27659950-e514665e-5c1a-11e7-9fc8-86b4da8e4547.png)

Ustedes nos avisan cuando podamos crear planes sin trial_period_days e indefinidos por fa.

Muchas gracias

Saludos

**Comment by eduardoconekta** [comment]
https://github.com/conekta/conekta-node/releases/tag/3.1.5 [RELEASE ]

**Comment by CarlosFloresSpoke** [comment]
Alguien puede ayudarme con el método para cancelar una suscripción, ya pude crear suscripción directamente desde el conekta.customer.create, solo le agregue el plan_id y listo
PERO NO SE COMO CANCELAR UNA SUSCRIPCIÓN,  estoy trabajando en NODEJS

**Comment by CarlosFloresSpoke** [comment]
Chicos, así creo mi suscripción. pero Cómo la cancelo
 var conekta = require('conekta');   
    conekta.api_key = 'key_hZW7jwFUg7WFxWvwgVyDyw';
    conekta.locale = 'es';

 

    if (meses == '1'){
        console.log(' pago por  1 mes');
        customer = conekta.Customer.create({
            'name': nom,
            'email': email,
            'phone': tel,
            "plan_id": "plan_basic_01",
            'metadata': { 'description': 'Compra de Subscripción $150 mensuales', 'reference': '1334523452345' },
            'payment_sources': [{
              'type': 'card',
              'token_id': token
            }],
            
          }, function(err, res) {
              if(err){
                console.log(err);
                return;
              }
              console.log(res.toObject());
              id_customer = res.toObject().id;
          });
          
      
    }
