### ISSUE TITLE
Couldn't capture pre_authorized order

### ISSUE THREAD

**Issue by WCLab** [conekta/conekta-node#39]
Hi, recently we've been integrating conekta api in nodejs.

We have this:

    api.order.capture = function(orderId){
	    return new Promise((resolve,reject)=>{
		console.log(orderId)
		Conekta.Order.find(orderId,function(err,order){
			console.log(err)
			console.log(order)
                       // All is dead here :S
			if(order)
                               if(order.capture())
				    resolve(order)
                                else
                                     reject({
                                          status:400,
                                          message: "Can't capture"
                                      })
			else
				reject({
					status: 404,
					message: "Order not found"
				})
		})
	    })
    }

Use

    conekta.order.capture("ord_2gyAfaTEQBPqZFwvp").then(success=>{
          res.send(success) //never run this
    }).catch(err=>{
          res.send(err) //   returns {}
    })

Following the official documentation, doest't work too

    var order = Conekta.Order.find("ord_2fw8EWJusiRrxdPzT");
    order.capture();

**Comment by WCLab** [comment]
Works now, thx.

**Comment by fredovm** [comment]
Hello! I would like to know if the following code is what worked for you?

let order = await conekta.Order.find("ord_2nn1NKbKPHdGZ4bmK")
if(order.capture())
   return "OK"
else
   return "BAD"
