### ISSUE TITLE
What is the correct format to send a reason when refund an order

### ISSUE THREAD

**Issue by WCLab** [conekta/conekta-node#40]
Hi, im trying to put a reason when refunding, but i've got "invalid format for reason"
     "code": "conekta.errors.parameter_validation.reason.invalid"

I want to send "Canceled by supervisor", sent "canceled_by_supervidor" and does not work too.

Regards!

**Comment by JoValo** [comment]
Hello @WCLab, in the documentation you can find the reasons available for the refunds. 
Note: Refunds are only possible on payments made by credit card or debit card.
Https://developers.conekta.com/api?vertical=event#refund-order

**Comment by WCLab** [comment]
Hi @JoValo, thank you so much. I had this link and types not listed:

https://developers.conekta.com/api?vertical=event#refund-order

Best regards!

**Comment by JoValo** [comment]
The reasons are the following, they do not change in the different verticals that we present in the documentation:
![Uploading Captura de pantalla 2017-08-10 a la(s) 12.59.50.png…]()
