### ISSUE TITLE
Error building npm

### ISSUE THREAD

**Issue by UvealSnow** [conekta/conekta-node#48]
I just installed conekta-node into my project as described and imported it to my main js file

`window.conekta = require('conekta');`
`window.conekta.api_key = 'public-key';`
`window.conekta.locale = 'es';`

when I try to build the project using `$ npm run watch` I get an error

ERROR in ./node_modules/conekta/lib/conekta.js
Module not found: Error: Can't resolve '../package' in '/Users/UvealSnow/laravel/disfruta/node_modules/conekta/lib'
 @ ./node_modules/conekta/lib/conekta.js 13:8-29
 @ ./resources/assets/js/store.js
 @ multi ./resources/assets/js/store.js

ERROR in ./node_modules/conekta/lib/conekta.js
Module not found: Error: Can't resolve 'fs' in '/Users/UvealSnow/laravel/disfruta/node_modules/conekta/lib'
 @ ./node_modules/conekta/lib/conekta.js 91:11-24
 @ ./resources/assets/js/store.js
 @ multi ./resources/assets/js/store.js

ERROR in ./node_modules/form-data/lib/form_data.js
Module not found: Error: Can't resolve 'fs' in '/Users/UvealSnow/laravel/disfruta/node_modules/form-data/lib'
 @ ./node_modules/form-data/lib/form_data.js 7:9-22
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/conekta/lib/conekta.js
 @ ./resources/assets/js/store.js
 @ multi ./resources/assets/js/store.js

ERROR in ./node_modules/request/lib/har.js
Module not found: Error: Can't resolve 'fs' in '/Users/UvealSnow/laravel/disfruta/node_modules/request/lib'
 @ ./node_modules/request/lib/har.js 3:9-22
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/conekta/lib/conekta.js
 @ ./resources/assets/js/store.js
 @ multi ./resources/assets/js/store.js

this is my package.json

```javascript
{
    "private": true,
    "scripts": {
    "dev": "npm run development",
    "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-poll": "npm run watch -- --watch-poll",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "prod": "npm run production",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
    "axios": "^0.16.2",
    "bootstrap-sass": "^3.3.7",
    "cross-env": "^5.0.1",
    "jquery": "^3.1.1",
    "laravel-mix": "^1.0",
    "lodash": "^4.17.4",
    "vue": "^2.1.10"
  },
  "dependencies": {
    "conekta": "^3.2.0",
    "font-awesome": "^4.7.0",
    "fs": "0.0.1-security",
    "net": "^1.0.2",
    "tls": "0.0.1",
    "vue-carousel": "^0.6.5",
    "vue-monthly-picker": "^0.1.4",
    "vue-select": "github:sagalbot/vue-select",
    "vue-spinner": "^1.0.3"
  }
}
```

**Comment by KarlaRobinson** [comment]
@UvealSnow Remember you can only use the Conekta node library for petitions from your backend, such as creating a charge.

Sensitive card information should tokenized through our front-end library Conekta.js
https://cdn.conekta.io/js/latest/conekta.js

More info here: https://developers.conekta.com/libraries/javascript

**Comment by UvealSnow** [comment]
Yes I am aware of that, the issue is this:

With a clean download of your package it will fail the asset compilation because of missing dependencies that conekta-node tries to fetch.

I'd like this to be fixed so I can implement the tokenization step to my JS framework.

**Comment by KarlaRobinson** [comment]
You had mentioned that you were trying to import the conekta-node library into your my main js file. 

Using only the conekta.js library you will be able to generate a token. 

You can then send this token(string), vía POST to your back end. There you should not have these errors when using the Conekta node library. 

If you still have missing dependency errors when integrating the library in your back end, or if I am misunderstanding your question please let us know!

**Comment by e-hop** [comment]
+1
