### ISSUE TITLE
Cert location incorrect

### ISSUE THREAD

**Issue by sanchezand** [conekta/conekta-node#50]
Just installed the module and copy pasted the test code.
When running it it gives me an error while opening the cert file.

```
Error: ENOENT: no such file or directory, open 'dev\node_modules\conekta\lib\cert\ca_bundle.crt'
      at Object.fs.openSync (fs.js:646:18)
      at Object.fs.readFileSync (fs.js:551:33)
      at Requestor.request (dev\node_modules\conekta\lib\conekta.js:97:16)
      at Object.post (dev\node_modules\conekta\lib\conekta.js:260:58)
      at Object.create (dev\node_modules\conekta\lib\conekta.js:362:10)
```
Looks like the cert file should be in `conekta\cert\ca_bundle.crt` not in `conekta\lib\cert\ca_bundle.crt`
Changing certPath in `conekta.js` to: 
`const certPath = path.join(path.dirname(__dirname), '/cert/ca_bundle.crt')`
fixed the problem.

Using conekta@3.3.1

**Comment by kiramishima** [comment]
Same problem, but the solution of @sanchezand fix the problem, good work @sanchezand 
Changing certPath in conekta.js to:
const certPath = path.join(path.dirname(__dirname), '/cert/ca_bundle.crt')

**Comment by eduenriquez** [comment]
this issue is already fixed
