### ISSUE TITLE
Plan create

### ISSUE THREAD

**Issue by nalancer08** [conekta/conekta-node#52]
When i create a plan, the amount always is downgrade, example:

If send 20000, in the Conekta console the plan has a cost of 200.00

Another things is, I can't send a decimal number 'cause automatically round, please upgrade this.

**Comment by mauroarcet** [comment]
Hi @nalancer08, the amount attribute is given in cents, 

e.g. $25.50 => amount = 2550

For any further questions, you can reach us at soporte@conekta.com
