### ISSUE TITLE
How to use conekta.js in React js

### ISSUE THREAD

**Issue by AnDyroHM** [conekta/conekta-node#55]
I need to use reactive js to send the token that generates conekta but when using the cdn and use Conekta.Token.Create (...) in the components of this one does not exist.
There is some library for front end to solve this problem?

**Comment by ea2305** [comment]
To handle external link with react.js application, you can put the CDN link in your HTML template to use it in all the components rendered with that template.
In the other hand, if you are using Webpack, you could check the external modules configuration of Webapack to use the library in your components: https://webpack.js.org/configuration/externals/

**Comment by cesargdm** [comment]
Please include a npm module to include at frontend bundles

**Comment by cesargdm** [comment]
By not including Conekta in my app bundle, you are taking a 1.4s delay in my render; please attend @ea2305 

<img width="708" alt="screen shot 2018-07-22 at 3 40 26 pm" src="https://user-images.githubusercontent.com/10179494/43049914-a4c9034c-8dc5-11e8-9bca-cf284e63ecb6.png">

**Comment by cesargdm** [comment]
@eduenriquez 

La idea es poder incluir Conekta para la tokenizacion de las tarjetas como una librería que pueda ser incluída en nuestros propios bundles de las aplicaciones, como sucede con cualquier otra librería, como lo haces con loadsh por ejemplo, puedes instalar el package, y en tu aplicación final lodash está incluído dentro del bundle de la aplicación, no en un de link script; esto no es factible para aplicaciones de alto desempeño.

**Comment by scarranca** [comment]
Any updates  ?

**Comment by a0nguyen** [comment]
Don't really understand why using conekta this way is 'factible para aplicaciones de alto desempeño', google maps is working the exact same way, and airbnb still includes it the same way you can include conekta.

1- In order to reduce render-blocking scripts, you can add conekta script in your highest order (probably your App.js) componentDidMount hook:

```
componentDidMount () {
  const script = document.createElement('script')
  script.src = 'https://cdn.conekta.io/js/latest/conekta.js'
  script.async = true
  document.body.appendChild(script)
}
```

2- To use conekta, you can just build a lil' helper:
```
import config from './config'

const conektaHelper = {
  initConekta: () => {
    window.Conekta.setPublicKey(config.conekta.staging.publicKey)
  },
  getCardBrand: (cardNumber) => {
    return window.Conekta.card.getBrand(cardNumber)
  },
  validateCardNumber: (cardNumber) => {
    return window.Conekta.card.validateNumber(cardNumber)
  },
  validateCvc: (cvc) => {
    return window.Conekta.card.validateCVC(cvc)
  },
  validateExpirationDate: (expiryMonth, expiryYear) => {
    return window.Conekta.card.validateExpirationDate(expiryMonth, `20${expiryYear}`)
  },
  tokenize: (cardNumber, cardHolder, expiryMonth, expiryYear, cvc, successCallback, errorCallback) => {
    const tokenParams = {
      card: {
        number: cardNumber,
        name: cardHolder,
        exp_year: expiryYear,
        exp_month: expiryMonth,
        cvc
      }
    }
    window.Conekta.Token.create(tokenParams, successCallback, errorCallback)
  }
}

export default conektaHelper
```

**Comment by alucard0** [comment]
Hi, I've a question, for React this NPM (https://www.npmjs.com/package/conekta-card-tokenizer ) is the latest? Or the only way to use Conekta is with the CDN https://cdn.conekta.io/js/latest/conekta.js

**Comment by e-hop** [comment]
+1 i need to implement this with react js

**Comment by salvadornava01** [comment]
> import config from './config'
> 
> const conektaHelper = {
>   initConekta: () => {
>     window.Conekta.setPublicKey(config.conekta.staging.publicKey)
>   },
>   getCardBrand: (cardNumber) => {
>     return window.Conekta.card.getBrand(cardNumber)
>   },
>   validateCardNumber: (cardNumber) => {
>     return window.Conekta.card.validateNumber(cardNumber)
>   },
>   validateCvc: (cvc) => {
>     return window.Conekta.card.validateCVC(cvc)
>   },
>   validateExpirationDate: (expiryMonth, expiryYear) => {
>     return window.Conekta.card.validateExpirationDate(expiryMonth, `20${expiryYear}`)
>   },
>   tokenize: (cardNumber, cardHolder, expiryMonth, expiryYear, cvc, successCallback, errorCallback) => {
>     const tokenParams = {
>       card: {
>         number: cardNumber,
>         name: cardHolder,
>         exp_year: expiryYear,
>         exp_month: expiryMonth,
>         cvc
>       }
>     }
>     window.Conekta.Token.create(tokenParams, successCallback, errorCallback)
>   }
> }
> 
> export default conektaHelper

This was the perfect solution, elegant and easy to integrate. I've tested it and it works. Thank you so much @a0nguyen

**Comment by AdrianMiranda137** [comment]
> Don't really understand why using conekta this way is not 'factible para aplicaciones de alto desempeño', google maps is working the exact same way, and airbnb still includes it the same way you can include conekta.
> 
> 1- In order to reduce render-blocking scripts, you can add conekta script in your highest order (probably your App.js) componentDidMount hook:
> 
> ```
> componentDidMount () {
>   const script = document.createElement('script')
>   script.src = 'https://cdn.conekta.io/js/latest/conekta.js'
>   script.async = true
>   document.body.appendChild(script)
> }
> ```
> 
> 2- To use conekta, you can just build a lil' helper:
> 
> ```
> import config from './config'
> 
> const conektaHelper = {
>   initConekta: () => {
>     window.Conekta.setPublicKey(config.conekta.staging.publicKey)
>   },
>   getCardBrand: (cardNumber) => {
>     return window.Conekta.card.getBrand(cardNumber)
>   },
>   validateCardNumber: (cardNumber) => {
>     return window.Conekta.card.validateNumber(cardNumber)
>   },
>   validateCvc: (cvc) => {
>     return window.Conekta.card.validateCVC(cvc)
>   },
>   validateExpirationDate: (expiryMonth, expiryYear) => {
>     return window.Conekta.card.validateExpirationDate(expiryMonth, `20${expiryYear}`)
>   },
>   tokenize: (cardNumber, cardHolder, expiryMonth, expiryYear, cvc, successCallback, errorCallback) => {
>     const tokenParams = {
>       card: {
>         number: cardNumber,
>         name: cardHolder,
>         exp_year: expiryYear,
>         exp_month: expiryMonth,
>         cvc
>       }
>     }
>     window.Conekta.Token.create(tokenParams, successCallback, errorCallback)
>   }
> }
> 
> export default conektaHelper
> ```

Hello, can you help me? What is ./config? it's a file that you create or it's something in all react's projects?

**Comment by luismasg** [comment]
its a files that has your password.
you create it, it is not included
