### ISSUE TITLE
Request: Promise interface

### ISSUE THREAD

**Issue by vangberg** [conekta/conekta-node#58]
It would be great if there was a version of your library which supported promises. Currently I have to wrap all Conekta funtions so it can work with my Promise-based workflow.

**Comment by GbalsaC** [comment]
Second that notion, Conekta should move documentation into ES6 support

**Comment by regenhans** [comment]
Yes please 👍

**Comment by eduenriquez** [comment]
Hi @vangberg thanks for the feedback we will have this requirement in mind and publish in the next releases

**Comment by KarlaRobinson** [comment]
We are working on a version that is compatible with promises. It should be released in a few days.

**Comment by KarlaRobinson** [comment]
Thanks for everyones suggestions. We have released a new version 3.5.2 which supports promises.
