### ISSUE TITLE
Conecta returns cached user [CRITICAL]

### ISSUE THREAD

**Issue by cesargdm** [conekta/conekta-node#60]
This is a critical issue.

By doing:

```
conekta.Customer.find(clientId, (err, customer) => {
      if (err) return reject(err)
      return resolve(customer)
    })
```

The first time that I look for a client with payment sources, it returns the data correctly; but the second request I look for another user with no payment sources, but I get back the payment sources from the previous user; and this with every subsequent request; I need to restart my server in order to stop receiving the previous user. Maybe this has to do with a cache that you're making in your library?

**Comment by cesargdm** [comment]
@andidev Until the PR is merged you could use the nom module I created https://www.npmjs.com/package/@nure/conekta

**Comment by javorosas** [comment]
any plans on publishing this update on the npm package?

**Comment by mkv27** [comment]
## With **conekta@3.6.1** | **latest**
Reproduce it with:
```js
var conekta = require('conekta')

conekta.api_key = 'API_KEY'
conekta.locale = 'es'

const a='CUSTOMER_ID_A', b='CUSTOMER_ID_B'
console.log('A:',a)
console.log('B:',b)

const findCustomer = (customerId) => new Promise((resolve, reject) => {
    conekta.Customer.find(customerId,function(err, res) {
        if (err) {
            console.log(err)
            return
        }
        resolve(res)
    })
})

const init = async () => {
    const aResponse = await findCustomer(a)
    const bResponse = await findCustomer(b)
    console.log('B:',bResponse._id)
    console.log('A:',aResponse._id)
}

init()
```
Test out:
```sh
A: CUSTOMER_ID_A
B: CUSTOMER_ID_B
B: CUSTOMER_ID_B
A: CUSTOMER_ID_B  # It should be CUSTOMER_ID_A
```

This error will be repeated if fx your server process asynchronous requests

**Comment by leofischer** [comment]
Thanks for the bug report @mkv27, we are going to look into this and will re-open the issue once we have reproduced it.

**Comment by leofischer** [comment]
@mkv27  - we have merged fixes for this in the latest release https://github.com/conekta/conekta-node/releases/tag/4.0.1. Can you confirm this works as expected? I will leave this issues open for another 2 weeks, and there are no further comments will close it as completed

**Comment by fcarrero** [comment]
closed it as completed
