### ISSUE TITLE
Version cliente en NPM  - ES6-

### ISSUE THREAD

**Issue by iamsteeve** [conekta/conekta-node#62]
Perdón por el español xD He visto muchos issues acerca de esto pero deben atenderlo de verdad necesitamos un paquete NPM para instalarse como una dependencia y poder requerirlo en mi aplicación javascript tengo 3 proyectos actualmente en ionic-angular que requieren el usar pasarelas de pago y me encanta conekta pero para tokenizar la tarjeta de credito rompe el estándar de mi aplicación y hablo por la mayoría de desarrolladores en react que incluirlo con script de forma externa hace que provoca problemas de rendimiento en la aplicación cuando lo único que queremos es tokenizar información de tarjeta. Y tenemos que ponernos a pensar a incluir a truño muy feo cuando se supone que esto debería agilizar el proceso de pago. 
Si se está trabajando para solucionar esto pues increíble pero si no... Estamos en el 2018 y creo que esto es más que una necesidad. Bueno es solo una recomendación perdonen de nuevo por hablar en español soy mexicano y me encanta conekta. Buen día c:

**Comment by cesargdm** [comment]
@eduenriquez

**Comment by eduenriquez** [comment]
@iamsteeve Gracias de verdad por darnos tu feedback recuerda que Conekta es tambien un producto hecho en México y para México asi que no te preocupes por el español, tienes algún ejemplo sobre alguna libreria que haga justo lo que necesitas hacer ? para que nosotros podamos ver como se implementa, y quiero creer que todo eso es para conekta.js verdad ?

**Comment by cesargdm** [comment]
Entiendo que solo buscamos que el script que se debe añadir pueda ser añadido como un módulo de npm para ser añadido en nuestros bundles de las aplicaciones, en el #55 he puesto desventajas de el método actual del script tag, no se si aún necesitarían ejemplos...

**Comment by iamsteeve** [comment]
Disculpe c: por tardar en contestar. Confirmo lo que comenta @cesargdm queremos solo un paquete que pueda ser agregado como dependencia por medio de import, estuve viendo el issue #55 y tengo la duda de que si puede ser instalado como dependencia con npm?? **npm i conekta-card-tokenizer** esto??? si es posible podré cerrar este issue xD cuando podría abrirse un repositorio para estos casos entiendo que muchos desarrolladores tendrán en un futuro estos detalles xD En especial al crear aplicaciones hibridas C: Saludos y gracias 👯‍♂️

**Comment by KarlaRobinson** [comment]
Cierro el issue porque hay una solución valida en issue https://github.com/conekta/conekta-node/issues/55
Gracias a todos por las contribuciones.
