### ISSUE TITLE
How to cancel or refund a pre-authorized order

### ISSUE THREAD

**Issue by andidev** [conekta/conekta-node#64]
How do I cancel a pre-authorized order? I can't call refund since I get the following error then:
```
{ http_code: 428,
  details:
   [ { debug_message: 'The order can not be returned.',
       message: 'The order can not be returned.',
       code:
        'conekta.errors.precondition_required.combo.order.is_not_returnable' } ],
  object: 'error',
  type: 'precondition_required_error',
  log_id: '5b8f0319b795b001b889066f' }
```

Calling refundOrder after capturing it probably works but it feels like the wrong way to do it.

**Comment by andidev** [comment]
Apparently this is done by sending a void POST request

```
curl -H "Accept: application/vnd.conekta-v2.0.0+json" \
 -H "Content-type: application/json" \
 -u key_y1ALCcyFVgGAghsjsjdSJ: \
 -X POST https://api.conekta.io/orders/ord_2iuxtxTJo3mNubxmV/void
```

though it does not seem to be supportet with this library.

**Comment by KarlaRobinson** [comment]
I am going to close this issue as we have merged your pr and the Node library now contains the void method.

**Comment by kalin89** [comment]
> Aparentemente esto se hace enviando una solicitud POST nula
> 
> ```
> curl -H "Accept: application/vnd.conekta-v2.0.0+json" \
>  -H "Content-type: application/json" \
>  -u key_y1ALCcyFVgGAghsjsjdSJ: \
>  -X POST https://api.conekta.io/orders/ord_2iuxtxTJo3mNubxmV/void
> ```
> 
> aunque no parece ser compatible con esta biblioteca.

I have the same problem with .Net, support tells me that I should send that post request, I understand that -H is "Header" but what does "-U" mean? Thanks for the help. I would be grateful if you could attach an image of how to make this request, either by code or a program such as postman, for example, thanks.
