### ISSUE TITLE
Dependencies have some vulnerabilities

### ISSUE THREAD

**Issue by bazquezero** [conekta/conekta-node#66]
After audit the package 7 moderate severity vulnerabilities were found

![screen shot 2018-10-06 at 09 18 57](https://user-images.githubusercontent.com/38488822/46572810-2841da00-c949-11e8-92bf-5e83e322cd73.png)
![screen shot 2018-10-06 at 09 19 29](https://user-images.githubusercontent.com/38488822/46572811-2841da00-c949-11e8-8ec7-1f3b2e013bb4.png)
![screen shot 2018-10-06 at 09 19 50](https://user-images.githubusercontent.com/38488822/46572812-2841da00-c949-11e8-9136-193b6576b190.png)

**Comment by fruizg0302** [comment]
Thanks @bazquezero I'm checking out those dependencies.

**Comment by javorosas** [comment]
Parece que todas estas vulnerabilidades vienen del módulo `request` el cual fue actualizado en #59 (now in master), pero no se ha publicado ninguna nueva versión de `conekta` en npm desde Abril, por lo tanto este cambio no está publicado y la versión actual sigue teniendo vulnerabilidades.

Sugiero publicar una nueva versión con todos los cambios añadidos desde Abril 🙂

**Comment by KarlaRobinson** [comment]
@bazquezero @javorosas Thanks and sorry for the delay! The newest version is available on npm and yarn:
https://www.npmjs.com/package/conekta
https://yarnpkg.com/en/package/conekta
