### ISSUE TITLE
Wrong card resource instancing

### ISSUE THREAD

**Issue by arathael** [conekta/conekta-node#7]
Using `v1.1.0`

When using `Customer.find()` the http response after JSON.parse() in your lib is:
```js
{ id: 'cus_P8yDUhp3RrDW5h2gE',
  ...
  default_card_id: 'card_7vV7hUQ2vWkKQt7F',
  object: 'customer',
  created_at: 1442370960,
  cards:
   [ { id: 'card_7vV7hUQ2vWkKQt7F',
       created_at: 1442551582,
       active: true,
       last4: '1001',
       ...
       customer_id: 'cus_P8yDUhp3RrDW5h2gE' },
     { id: 'card_8Rusp3ktxiaGy4Zo',
       created_at: 1442553885,
       active: true,
       last4: '0485',
       ...
       customer_id: 'cus_P8yDUhp3RrDW5h2gE' } ],
  subscription: null }
```
All of the card objects have different IDs.

Then in your wrapper you append member methods to this object and pass it on to the user callback, so in my code I `console.log(customer.toObject().cards)` or `console.log(customer._json.cards)` and get the original response:
```js
[ { id: 'card_7vV7hUQ2vWkKQt7F',
    created_at: 1442551582,
    active: true,
    last4: '1001',
    object: 'card',
    ...
    customer_id: 'cus_P8yDUhp3RrDW5h2gE' },
  { id: 'card_8Rusp3ktxiaGy4Zo',
    created_at: 1442553885,
    active: true,
    last4: '0485',
    ...
    customer_id: 'cus_P8yDUhp3RrDW5h2gE' } ]
```
But when actually logging `customer` or `customer.cards` I found that all the card objects you return have the same `_id` (the last card `id`):
```js
[ { _id: 'card_8Rusp3ktxiaGy4Zo',
    classUrl: '/customers',
    members: {},
    _json:
     { id: 'card_8Rusp3ktxiaGy4Zo',
       created_at: 1442553885,
       active: true,
       last4: '0485',
       ...
    createMembers: [Function],
    get: [Function],
    post: [Function],
    put: [Function],
    del: [Function],
    custom: [Function],
    update: [Function],
    delete: [Function] },
  { _id: 'card_8Rusp3ktxiaGy4Zo',
    classUrl: '/customers',
    members: {},
    _json:
     { id: 'card_8Rusp3ktxiaGy4Zo',
       created_at: 1442553885,
       active: true,
       last4: '0485',
       ...
       customer_id: 'cus_P8yDUhp3RrDW5h2gE' },
    _items: [],
    toObject: [Function],
    toArray: [Function],
    createMembers: [Function],
    get: [Function],
    post: [Function],
    put: [Function],
    del: [Function],
    custom: [Function],
    update: [Function],
    delete: [Function] } ]
```
This behavior makes impossible to delete a card by ID, because when trying to `_.findIndex()` or something you get `-1` because the only thing in that array is the last card over and over again.

If I `_.findIndex()` over your `.toObject()` or `._json` values I get the right index, but when trying to `customer.cards[index].delete()` the card with the repeated `_id` gets deleted, not the one I was trying to remove.

**Comment by julianceballos** [comment]
@arathael thanks for create this bug, i'll be fixing it for next tuesday release.

**Comment by arathael** [comment]
¡Gracias!

**Comment by julianceballos** [comment]
This issue has been fixed @arathael Thanks for your feedback :dancer:

**Comment by arathael** [comment]
Thanks, I'll run my tests again and let you know what happened.
