### ISSUE TITLE
Cannot delete payment source

### ISSUE THREAD

**Issue by cesargdm** [conekta/conekta-node#70]
When I try to delete a payment source from a customer I get an error. I found out that in the docs the argument that is supposed to passed is the payment source's id, but the library function works with the desired payment source's **index**, that's why is not working. Fix?

**Comment by fruizg0302** [comment]
Hey @cesargdm Gracias por abrir el issue, deja lo checo y vuelvo contigo.

**Comment by cesargdm** [comment]
Lo siento, es un duplicado de #69, sucedió cuando se cayó Github
