### ISSUE TITLE
How can I use other card

### ISSUE THREAD

**Issue by CardeDeveloper** [conekta/conekta-node#80]
A typical request to create an order:

`conekta.Order.create({
  "currency": "MXN",
  "customer_info": {
    "customer_id": "cus_zzmjKsnM9oacyCwV3"
  },
  "line_items": [{
    "name": "Box of Cohiba S1s",
    "unit_price": 35000,
    "quantity": 1
  }],
  "charges": [{
    "payment_method": {
      "type": "default"
    }
  }]
}, function(err, order) {
    console.log(order.toObject());
})`

**In payment_method**

I want to use an Id from other card that's not the default I set an object like this:
`"payment_method": {
      'type': 'card',
      'id': 'cus_2kSYXgdHQ1wgdGAJt'
    }  `

and doesnt works because I require a  token_id (also i tried changing id to token_id) but I cant tokenize a card from backend, How can I select a different card?

at the moment the unique way is changing the default card

**Comment by herel** [comment]
Amigo estoy con el mismo problema, ¿Como lo has solucionado?

**Comment by leofischer** [comment]
This should work using something like this:

```json
{"payment_method": { 'type': 'card', 'payment_source_id': 'src_8f8dea980123bcassc' }}
```

I am flagging this as a documentation issue and will cross check against other plugins.

**Comment by ivanNieto13** [comment]
> ```json
> payment_source_id
> ```

Thanks. But still not seeing in documentation.
