### ISSUE TITLE
Updating payment source without index

### ISSUE THREAD

**Issue by kr05** [conekta/conekta-node#82]
I am trying to update a customer's payment source and according to the tutorial we have to use the following method:

```javascript
conekta.Customer.find("cus_zzmjKsnM9oacyCwV3", function(err, customer) {
  customer.payment_sources.get(0).update({ exp_month: 11 },
  function(err, paymentSource) {
    console.log(paymentSource);
  });
});
```

My questions is...can we update a payment source using its ID instead of the array index? I tried passing the ID into the get method, but it throws an error. My second attempt was to store the index when creating the payment source, but unfortunately the index is not returned when creating a payment source using the createPaymentSource method. I would appreciate any pointers and suggestions, thanks!

**Comment by javorosas** [comment]
+1, this would be ideal

**Comment by humbertowoody** [comment]
+1, why is this not the default? D:

**Comment by leofischer** [comment]
+1, id would definitely make a lot more sense and there appears to be several issues related to the usability of payment source arrays.  Am flagging this as an enhancement.
