### ISSUE TITLE
Unable to delete payment source when index exceeds 4

### ISSUE THREAD

**Issue by alfredoqt** [conekta/conekta-node#84]
I am currently testing with a client that has 8 payment sources. When I try to delete a payment source with an index greater than 4, your sdk crashes.

> 2019-06-18T22:39:51.422Z	ad5728a1-31bd-4899-8c62-342cec6d4a4c	INFO	TypeError: Cannot read property 'id' of undefined
at Object.get (/var/task/node_modules/conekta/lib/resources/Card.js:8:42)
at Runtime.exports.handler (/var/task/index.js:44:62)
at process._tickCallback (internal/process/next_tick.js:68:7) 'TypeError: Cannot read property \'id\' of undefined\n at Object.get (/var/task/node_modules/conekta/lib/resources/Card.js:8:42)\n at Runtime.exports.handler (/var/task/index.js:44:62)\n at process._tickCallback (internal/process/next_tick.js:68:7)'

**Comment by leofischer** [comment]
That sounds like pretty weird behavior, can you attach a code snippet to reproduce?

**Comment by leofischer** [comment]
There was some unexpected behavior when iterating over embedded resources which has been improved by this PR https://github.com/conekta/conekta-node/pull/99.  Previously performing .get() on an embedded resource would return the sub-object and replace the list object, this PR should correct this issue.

**Comment by leofischer** [comment]
@alfredoqt - I have merged corrections in the latest release https://github.com/conekta/conekta-node/releases/tag/4.0.1.  Can you confirm this works as expected?  I will leave this issues open for another 2 weeks, and there are no further comments will close it as completed

**Comment by fcarrero** [comment]
@leofischer can you close this issue ?
we did not receive any feedback during long period of time.

**Comment by fcarrero** [comment]
i close this pr due to inactivity
