### ISSUE TITLE
Conekta en VUEJS?

### ISSUE THREAD

**Issue by Razielini** [conekta/conekta-node#89]
Como usar el generador de token de Conekta para una aplicación en VueJS?

Intento usar esto:
https://www.npmjs.com/package/conekta-card-tokenizer

Pero es muy viejo y no funciona.

Tienen alguna solución? En la documentación oficial no hay nada al respecto.

Nota: Uso Vuejs CLI + Typescript.

**Comment by aguilera51284** [comment]
Increible que sigan con esos hacks :(

**Comment by Razielini** [comment]
De hecho lo resolví de otra manera mas simple, en el index.html que esta en public, lo puedes añadir como dice la documentación y funciona, salvo que el TSLint te da muchos errores por que no lo reconoce.

Hubiera preferido un npm pero es lo que hay.
