### ISSUE TITLE
How to use the `.where` filter?

### ISSUE THREAD

**Issue by humbertowoody** [conekta/conekta-node#91]
The documentation specifies [in the "Endpoints" section](https://github.com/conekta/conekta-node#endpoints) the endpoint: `Conekta.order.where`. I am trying to get all the Orders related to a Customer, however there is no documentation regarding the search criteria for the `where` statement. Is there a way to make `where` work this way? What would be the format for the argument of the endpoint? There isn't an endpoint like `Conekta.Customer.orders` which can be used that way? 

Thanks in advance!

EDIT: Add a sample of my current implementation to which the Conekta API is returning a `422` HTTP status code:

```javascript
// Get the the Orders for the Customer from Conekta.
const orders = await conekta.Order.where({
  customer_info: { customer_id: user.conektaId },
});
console.log(orders.toObject());
```

**Comment by humbertowoody** [comment]
It seems to be an issue with the underlying [qs parser](https://github.com/ljharb/qs#parsing-objects) within the `request` library which is transforming the initial query object:

```javascript
{
  customer_info: { customer_id: user.conektaId },
}
```

Into: `?customer_info[customer_id]=cus_XXXXX` instead of `?customer_info.customer_id=cus_XXX`.

As there **is not** any documentation regarding the format for the endpoint, I checked how you guys are using it in the [Conekta Admin application](https://admin.conekta.com) and noticed the correct format which is: `customer_info.customer_id=cus_XXX` which is different from the output of the `qs` package.

Perhaps I can create a PR with a fix but some documentation of your query parsing mechanism would be nice! :)

**Comment by humbertowoody** [comment]
As a workaround, and if anyone runs into the same issue:

```javascript
{
  "customer_info.customer_id": 'cus_XXXX',
}
```
Does the trick! However, the option `allowDots` from `qs` should fix the issue.

**Comment by leofischer** [comment]
Hi @humbertowoody, thats for reporting (and debugging) this issue!  Would you like to submit a PR for this, and if not, could you confirm if this is where you made the change and what changes you made? https://github.com/conekta/conekta-node/blob/07e903787b03e51834aa4867c70368d97f35e36b/lib/Requestor.js#L82

**Comment by leofischer** [comment]
A PR for this issue is now pending review - https://github.com/conekta/conekta-node/pull/94.  The documentation for resource searching will be managed in a separate high level issue: https://github.com/conekta/docs/issues/449.

**Comment by fcarrero** [comment]
i close this pr due to inactivity
