### ISSUE TITLE
Monto de orden creada se refleja incorrectamente en el panel administrativo de conekta

### ISSUE THREAD

**Issue by Hellogark** [conekta/conekta-node#92]
No se si este problema es relacionado con la api o con el panel administrativo de conekta, al momento de crear la orden, el precio de un artículo es 
![montos](https://user-images.githubusercontent.com/25800442/68793039-baff7e80-0609-11ea-8b30-7e7c3e156dcb.PNG)
23212, pero en el panel administrativo se muestra cómo $232.12 en el modo de prueba, los últimos dos dígitos los toma cómo centavos. Intenté multiplicar *100 el valor de unit price pero me regresa un error diciendo que el monto máximo para tarjetas es de 5000 MXN

**Comment by leofischer** [comment]
Hola @Hellogark,

Ya revisé tu caso, al parecer tu sistema está multiplicando este precio por 100.  Supongo que está esperando un monto en pesos, luego lo multiplica para mandarlo a nosotros en centavos.  Puedes confirmar buscando el log con el log_id que viene allí (5dcc4c8e431e725fbb4430b2) en tu admin.  Por ejemplo, el cuerpo de la petición que recibimos en este caso fue el siguiento, lo cual lleva un monto de 23,212.00 pesos:

```json
{
  "currency": "MXN",
  "customer_info": {
    "name": "dsfdfklj",
    "phone": "6684637700",
    "email": "kjdfs@sdkdf.sdf"
  },
  "line_items":[{
    "name": "Paquete caro",
    "unit_price": 2321200,
    "quantity": 1
  }],
  "charges": [{
    "payment_method":
      {
        "type": "card",
        "token_id": "tok_test_visa_4242"
      }
    }
  ]
}
```

**Comment by Hellogark** [comment]
El sistema está bien, había probado si se podía multiplicar la cantidad por 100 para ver si se reflejaba la cantidad correcta en el panel administrativo, pero por alguna razón ya que llega la cantidad al panel administrativo se divide entre 100, la cantidad es correcta y no se hace actualmente ninguna modificación a la cantidad, tenemos planeado manejar cantidades de hasta $100,000 por transacción.

**Comment by leofischer** [comment]
Osea, el monto que quieres cobrar es de 23,212.00?  En este caso el monto que tienes es correcto, y los de 232.12 tendrían que ser casos distintos.  El error que capturaste fue un ParameterValidationError y tal cual no va generar el order.   El motivo del rechazo es porque el monto máximo configurado para tu compañía es de 5000 MXN, para procesar montos más altos tendrías que seguir el proceso de activación para que lo ajusten.

**Comment by Hellogark** [comment]
Entiendo del monto máximo para pruebas, de hecho quise intentar con un monto más pequeño, cómo $300, pero me arrojaba un error que el monto mínimo deberían de ser $30 o $50 algo por el estilo

**Comment by leofischer** [comment]
Mmm, sí, parece que hay algo allí con la división.  Si mandas un monto al api de 30000 eso va generar un order de monto $ 300 MXN.  Si te está arrojando algo distinto podrías buscar la petición en la sección de los en el admin para poder ver lo que estamos recibiendo.

**Comment by Hellogark** [comment]
Generé un cobro por SPEI de $30,000 y en efecto me genera  $300 en el panel administrativo, por lo que dices me das a entender que el monto en el modo de pruebas se divide por lo mismo de evitar excederse de los $5,000? Cómo sabría si funciona de forma correcta el pago en el modo de producción? lo pregunto porque hacer pruebas en producción para saber si sí funciona de manera correcta me parece ilógico

**Comment by Hellogark** [comment]
Para cerrar el issue, el monto se debe de multiplicar *100 para poder tener la cantidad en pesos, desconozco el porqué lo manejan en centavos la cantidad, pero si es confuso tener que estar haciendo esa multiplicación.

**Comment by TrejoCode** [comment]
Me sucede lo mismo, es algo que deben solucionar.

**Comment by silvaGarduno** [comment]
Hola @TrejoCode , que problema presentas? tienes alguna duda o problema con el que quieras que te apoyemos?

**Comment by TrejoCode** [comment]
> Hola @TrejoCode , que problema presentas? tienes alguna duda o problema con el que quieras que te apoyemos?

El mismo, yo envío 1200 MXN y en el panel me muestra: $12 MXN.

**Comment by silvaGarduno** [comment]
ok, multiplica los 1200 * 100, esto porque tenemos que transformar los pesos a centavos, es así como se guardan los montos en API.

**Comment by TrejoCode** [comment]
> ok, multiplica los 1200 * 100, esto porque tenemos que transformar los pesos a centavos, es así como se guardan los montos en API.

De acuerdo, eso mismo realicé, de mi parte no encontré esa descripción en la documentación, simplemente como recomendación sería bueno especificarlo.
Gracias por la ayuda.
